name: new-api-proxy
on: 
  push:
    branches:
      - main

jobs:
  run_proxy_bundle:
    if: contains(github.event.head_commit.message, 'new_proxy_bundle')
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      APIGEE_ORG: b2b-apigee-sb
      APIGEE_ENV: eval
      PROXY_NAME: transversal-petstore-v1
      OPENAPI_SPEC_FILEPATH: ./petStore.yaml
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        token_format: "access_token"
        create_credentials_file: true
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: Installing dependencies
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         sudo apt-get update
         sudo apt-get install -y \
         jq \
         curl \
         npm \
         python3
         npm i -g openapi2apigee

    - name: Checking Versions
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         echo "npm version: ";npm -version
         echo "openapi2apigee version: "; openapi2apigee -V
         echo "curl version: ";curl -V

    - name: Creating new proxy bundle
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         openapi2apigee generateApi $PROXY_NAME -s $OPENAPI_SPEC_FILEPATH -d ./
         mv $PROXY_NAME/apiproxy.zip ./
         rmdir -r $PROXY_NAME
         echo; pwd;ls -ltr
         
    - name: Upload new proxy bundle
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         export GCLOUD_TOKEN=${{steps.auth.outputs.access_token}}
         chmod +x deploy_curl.sh
         ./deploy_curl.sh
      shell: bash

    - name: Commit and push bundle
      uses: EndBug/add-and-commit@v9
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      with:
        default_author: github_actions
        message: 'Se agrega la carpeta zip del API Proxy generado'
        push: origin --set-upstream --force