name: new-api-proxy
on: 
  push:
    branches:
      - main

jobs:
  run_proxy_bundle:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      APIGEE_ORG: b2b-apigee-sb
      APIGEE_ENV: eval
    steps:
    - uses: actions/checkout@v2
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        token_format: "access_token"
        create_credentials_file: true
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: Installing dependencies
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         sudo apt-get update
         sudo apt-get install -y \
         jq \
         curl \
         npm \
         python3
         npm i -g openapi2apigee
         curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-400.0.0-linux-x86_64.tar.gz
         tar -xf google-cloud-cli-400.0.0-linux-x86_64.tar.gz
         ./google-cloud-sdk/install.sh --quiet

    - name: Checking Versions
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         echo "npm version: ";npm -version
         echo "openapi2apigee version: "; openapi2apigee -V
         echo "curl version: ";curl -V
         echo "gcloud version: ";./google-cloud-sdk/bin/gcloud --version

    - name: Creating new proxy bundle
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         openapi2apigee generateApi petStore -s ./petStore.yaml -d ./
         echo; pwd;ls -ltr petStore/apiproxy
         
    - name: Upload new proxy bundle
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      run: |
         export GCLOUD_TOKEN=${{steps.auth.outputs.access_token}}
         chmod +x deploy_curl.sh
         ./deploy_curl.sh
      shell: bash

    - name: Commit and push bundle
      uses: EndBug/add-and-commit@v9
      if: contains(github.event.head_commit.message, 'new_proxy_bundle')
      with:
        add: ./petStore
        default_author: github_actions
        message: 'Se agrega la carpeta del API Proxy generado con variable en el nombre'
        push: origin --set-upstream --force